window.CONTINUANCE_COUNTRY_MAP = {
  "United States of America": "USA",
  "Canada": "CAN",
  "United Kingdom": "GBR",
  "Russia": "RUS",
  "Thailand": "THA",
  "Laos": "LAO",
  "Cambodia": "KHM",
  "Vietnam": "VNM",
  "Norway": "NOR",
  "Sweden": "SWE",
  "Denmark": "DNK",
  "Finland": "FIN",
  "China": "CHN",
  "Switzerland": "CHE",
  "Cuba": "CUB",
  "Germany": "DEU",
  "France": "FRA",
  "Japan": "JPN",
  "Brazil": "BRA",
  "Costa Rica": "CRI",
  "Panama": "PAN",
  "Trinidad and Tobago": "TTO",
  "Austria": "AUT",
  "Argentina": "ARG",
  "Bolivia": "BOL",
  "Greenland": "GRL",
  "Luxembourg": "LUX",
  "Netherlands": "NLD",
  "North Korea": "PRK",
  "Mozambique": "MOZ",
  "Angola": "AGO",
  "Saudi Arabia": "SAU",
  "Kenya": "KEN",
  "Romania": "ROU",
  "Australia": "AUS",
  "Iceland": "ISL",
  "Faeroe Is.": "FRO"
};
